### ISSUE TITLE
Could not map to virtual file

### ISSUE THREAD

**Issue by anancds** [leimao/gRPC_Examples#1]
when i execute the following command, I encountered an error:
cmake ..
make

The error is :

Could not map to virtual file: /home/cds/code/gRPC_Examples/build/protos: Input file is a directory.
protos/CMakeFiles/greetings.grpc.dir/build.make:71: recipe for target 'protos/protos.pb.cc' failed
make[2]: *** [protos/protos.pb.cc] Error 1
CMakeFiles/Makefile2:91: recipe for target 'protos/CMakeFiles/greetings.grpc.dir/all' failed
make[1]: *** [protos/CMakeFiles/greetings.grpc.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by leimao** [comment]
Thank you for pointing this out. The FindGPRC module is not working with the latest gRPC anymore. I will try to upgrade the repo soon to remove the error. If you have a working solution now, please file a pull request. Thank you very much.

**Comment by leimao** [comment]
@anancds The CMake build has now been fixed. Feel free to open a new issue if you encounter any. Thank you.

**Comment by iotbyanurag** [comment]
CMake Error at CMakeLists.txt:9 (find_package):
  Could not find a package configuration file provided by "Protobuf" with any
  of the following names:

    ProtobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set
  "Protobuf_DIR" to a directory containing one of the above files.  If
  "Protobuf" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by leimao** [comment]
> CMake Error at CMakeLists.txt:9 (find_package): Could not find a package configuration file provided by "Protobuf" with any of the following names:
> 
> ```
> ProtobufConfig.cmake
> protobuf-config.cmake
> ```
> 
> Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set "Protobuf_DIR" to a directory containing one of the above files. If "Protobuf" provides a separate development package or SDK, be sure it has been installed.

Please use Docker container and follow the instructions in README.
