### ISSUE TITLE
-- Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by iotbyanurag** [leimao/gRPC_Examples#3]
CMake Error at CMakeLists.txt:9 (find_package):
  Could not find a package configuration file provided by "Protobuf" with any
  of the following names:

    ProtobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set
  "Protobuf_DIR" to a directory containing one of the above files.  If
  "Protobuf" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

**Comment by leimao** [comment]
Please use Docker container and follow the instructions in README.
